### ISSUE TITLE
Cant change default webviw implementation

### ISSUE THREAD

**Issue by Barshan-Mandal** [WSA-Community/WSA-Linux-Kernel#2]
Micro g problem

**Comment by Barshan-Mandal** [comment]
Why is it invalid bro?Without changing it I cant sign in using micro g

**Comment by MlgmXyysd** [comment]
You may have come to the wrong place, here is the kernel

**Comment by Barshan-Mandal** [comment]
Where should i submit this issue?I think it is the part of the kernel
